//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.ClientProxy.Lavanderia.OrdenProduccionLavanderiaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenProduccionLavanderiaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class OrdenProduccionLavanderiaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadEntradaLavanderia2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadFinalEnsambleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadPendienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CentroTrabajoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CompaniaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinalProgramadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioProgramadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LavadoCodigoOldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LavadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LavadoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PesoUnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlantaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaProduccionCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaVentaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarianteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((this.AnoField.Equals(value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantidadEntradaLavanderia2 {
            get {
                return this.CantidadEntradaLavanderia2Field;
            }
            set {
                if ((this.CantidadEntradaLavanderia2Field.Equals(value) != true)) {
                    this.CantidadEntradaLavanderia2Field = value;
                    this.RaisePropertyChanged("CantidadEntradaLavanderia2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantidadFinalEnsamble {
            get {
                return this.CantidadFinalEnsambleField;
            }
            set {
                if ((this.CantidadFinalEnsambleField.Equals(value) != true)) {
                    this.CantidadFinalEnsambleField = value;
                    this.RaisePropertyChanged("CantidadFinalEnsamble");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantidadPendiente {
            get {
                return this.CantidadPendienteField;
            }
            set {
                if ((this.CantidadPendienteField.Equals(value) != true)) {
                    this.CantidadPendienteField = value;
                    this.RaisePropertyChanged("CantidadPendiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CentroTrabajoId {
            get {
                return this.CentroTrabajoIdField;
            }
            set {
                if ((this.CentroTrabajoIdField.Equals(value) != true)) {
                    this.CentroTrabajoIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CompaniaId {
            get {
                return this.CompaniaIdField;
            }
            set {
                if ((this.CompaniaIdField.Equals(value) != true)) {
                    this.CompaniaIdField = value;
                    this.RaisePropertyChanged("CompaniaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinalProgramada {
            get {
                return this.FechaFinalProgramadaField;
            }
            set {
                if ((this.FechaFinalProgramadaField.Equals(value) != true)) {
                    this.FechaFinalProgramadaField = value;
                    this.RaisePropertyChanged("FechaFinalProgramada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicioProgramada {
            get {
                return this.FechaInicioProgramadaField;
            }
            set {
                if ((this.FechaInicioProgramadaField.Equals(value) != true)) {
                    this.FechaInicioProgramadaField = value;
                    this.RaisePropertyChanged("FechaInicioProgramada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LavadoCodigoOld {
            get {
                return this.LavadoCodigoOldField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoCodigoOldField, value) != true)) {
                    this.LavadoCodigoOldField = value;
                    this.RaisePropertyChanged("LavadoCodigoOld");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LavadoId {
            get {
                return this.LavadoIdField;
            }
            set {
                if ((this.LavadoIdField.Equals(value) != true)) {
                    this.LavadoIdField = value;
                    this.RaisePropertyChanged("LavadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LavadoNombre {
            get {
                return this.LavadoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoNombreField, value) != true)) {
                    this.LavadoNombreField = value;
                    this.RaisePropertyChanged("LavadoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patron {
            get {
                return this.PatronField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronField, value) != true)) {
                    this.PatronField = value;
                    this.RaisePropertyChanged("Patron");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PesoUnidad {
            get {
                return this.PesoUnidadField;
            }
            set {
                if ((this.PesoUnidadField.Equals(value) != true)) {
                    this.PesoUnidadField = value;
                    this.RaisePropertyChanged("PesoUnidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlantaId {
            get {
                return this.PlantaIdField;
            }
            set {
                if ((this.PlantaIdField.Equals(value) != true)) {
                    this.PlantaIdField = value;
                    this.RaisePropertyChanged("PlantaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaProduccionCodigo {
            get {
                return this.TelaProduccionCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaProduccionCodigoField, value) != true)) {
                    this.TelaProduccionCodigoField = value;
                    this.RaisePropertyChanged("TelaProduccionCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaVentaCodigo {
            get {
                return this.TelaVentaCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaVentaCodigoField, value) != true)) {
                    this.TelaVentaCodigoField = value;
                    this.RaisePropertyChanged("TelaVentaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variante {
            get {
                return this.VarianteField;
            }
            set {
                if ((object.ReferenceEquals(this.VarianteField, value) != true)) {
                    this.VarianteField = value;
                    this.RaisePropertyChanged("Variante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdenProduccionLavanderiaServiceReference.IOrdenProduccionLavanderia")]
    public interface IOrdenProduccionLavanderia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionLavanderia/Get", ReplyAction="http://tempuri.org/IOrdenProduccionLavanderia/GetResponse")]
        Intermoda.ClientProxy.Lavanderia.OrdenProduccionLavanderiaServiceReference.OrdenProduccionLavanderiaBusiness[] Get(short companiaId, int plantId, short centroTrabajoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionLavanderia/Get", ReplyAction="http://tempuri.org/IOrdenProduccionLavanderia/GetResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.OrdenProduccionLavanderiaServiceReference.OrdenProduccionLavanderiaBusiness[]> GetAsync(short companiaId, int plantId, short centroTrabajoId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenProduccionLavanderiaChannel : Intermoda.ClientProxy.Lavanderia.OrdenProduccionLavanderiaServiceReference.IOrdenProduccionLavanderia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenProduccionLavanderiaClient : System.ServiceModel.ClientBase<Intermoda.ClientProxy.Lavanderia.OrdenProduccionLavanderiaServiceReference.IOrdenProduccionLavanderia>, Intermoda.ClientProxy.Lavanderia.OrdenProduccionLavanderiaServiceReference.IOrdenProduccionLavanderia {
        
        public OrdenProduccionLavanderiaClient() {
        }
        
        public OrdenProduccionLavanderiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenProduccionLavanderiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenProduccionLavanderiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenProduccionLavanderiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Intermoda.ClientProxy.Lavanderia.OrdenProduccionLavanderiaServiceReference.OrdenProduccionLavanderiaBusiness[] Get(short companiaId, int plantId, short centroTrabajoId) {
            return base.Channel.Get(companiaId, plantId, centroTrabajoId);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.OrdenProduccionLavanderiaServiceReference.OrdenProduccionLavanderiaBusiness[]> GetAsync(short companiaId, int plantId, short centroTrabajoId) {
            return base.Channel.GetAsync(companiaId, plantId, centroTrabajoId);
        }
    }
}
