//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelaColorIntermodaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class TelaColorIntermodaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.ColorIntermodaBusiness ColorIntermodaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorIntermodaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.CatalogoBusiness MaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaterialIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaBusiness TelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.ColorIntermodaBusiness ColorIntermoda {
            get {
                return this.ColorIntermodaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorIntermodaField, value) != true)) {
                    this.ColorIntermodaField = value;
                    this.RaisePropertyChanged("ColorIntermoda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColorIntermodaId {
            get {
                return this.ColorIntermodaIdField;
            }
            set {
                if ((this.ColorIntermodaIdField.Equals(value) != true)) {
                    this.ColorIntermodaIdField = value;
                    this.RaisePropertyChanged("ColorIntermodaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.CatalogoBusiness Material {
            get {
                return this.MaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialField, value) != true)) {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaterialId {
            get {
                return this.MaterialIdField;
            }
            set {
                if ((this.MaterialIdField.Equals(value) != true)) {
                    this.MaterialIdField = value;
                    this.RaisePropertyChanged("MaterialId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaBusiness Tela {
            get {
                return this.TelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaField, value) != true)) {
                    this.TelaField = value;
                    this.RaisePropertyChanged("Tela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaId {
            get {
                return this.TelaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaIdField, value) != true)) {
                    this.TelaIdField = value;
                    this.RaisePropertyChanged("TelaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorIntermodaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class ColorIntermodaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class CatalogoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaContableCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaContableInventarioCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaVariableFijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedidaCompraCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedidaConsumoCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepuestoNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoRequisicionCodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaContableCodigo {
            get {
                return this.CuentaContableCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaContableCodigoField, value) != true)) {
                    this.CuentaContableCodigoField = value;
                    this.RaisePropertyChanged("CuentaContableCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaContableInventarioCodigo {
            get {
                return this.CuentaContableInventarioCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaContableInventarioCodigoField, value) != true)) {
                    this.CuentaContableInventarioCodigoField = value;
                    this.RaisePropertyChanged("CuentaContableInventarioCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaVariableFija {
            get {
                return this.CuentaVariableFijaField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaVariableFijaField, value) != true)) {
                    this.CuentaVariableFijaField = value;
                    this.RaisePropertyChanged("CuentaVariableFija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoCodigo {
            get {
                return this.GrupoCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoCodigoField, value) != true)) {
                    this.GrupoCodigoField = value;
                    this.RaisePropertyChanged("GrupoCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedidaCompraCodigo {
            get {
                return this.MedidaCompraCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedidaCompraCodigoField, value) != true)) {
                    this.MedidaCompraCodigoField = value;
                    this.RaisePropertyChanged("MedidaCompraCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedidaConsumoCodigo {
            get {
                return this.MedidaConsumoCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedidaConsumoCodigoField, value) != true)) {
                    this.MedidaConsumoCodigoField = value;
                    this.RaisePropertyChanged("MedidaConsumoCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepuestoNumero {
            get {
                return this.RepuestoNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.RepuestoNumeroField, value) != true)) {
                    this.RepuestoNumeroField = value;
                    this.RaisePropertyChanged("RepuestoNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaCodigo {
            get {
                return this.TelaCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaCodigoField, value) != true)) {
                    this.TelaCodigoField = value;
                    this.RaisePropertyChanged("TelaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoRequisicionCodigo {
            get {
                return this.TipoRequisicionCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoRequisicionCodigoField, value) != true)) {
                    this.TipoRequisicionCodigoField = value;
                    this.RaisePropertyChanged("TipoRequisicionCodigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class TelaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComposicionNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaterialCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComposicionNombre {
            get {
                return this.ComposicionNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ComposicionNombreField, value) != true)) {
                    this.ComposicionNombreField = value;
                    this.RaisePropertyChanged("ComposicionNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaterialCodigo {
            get {
                return this.MaterialCodigoField;
            }
            set {
                if ((this.MaterialCodigoField.Equals(value) != true)) {
                    this.MaterialCodigoField = value;
                    this.RaisePropertyChanged("MaterialCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaCodigo {
            get {
                return this.TelaCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaCodigoField, value) != true)) {
                    this.TelaCodigoField = value;
                    this.RaisePropertyChanged("TelaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaDescripcion {
            get {
                return this.TelaDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaDescripcionField, value) != true)) {
                    this.TelaDescripcionField = value;
                    this.RaisePropertyChanged("TelaDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaNombre {
            get {
                return this.TelaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaNombreField, value) != true)) {
                    this.TelaNombreField = value;
                    this.RaisePropertyChanged("TelaNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TelaColorIntermodaServiceReference.ITelaColorIntermoda")]
    public interface ITelaColorIntermoda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/Update", ReplyAction="http://tempuri.org/ITelaColorIntermoda/UpdateResponse")]
        Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness Update(Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness telaColorIntermoda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/Update", ReplyAction="http://tempuri.org/ITelaColorIntermoda/UpdateResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness telaColorIntermoda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/Delete", ReplyAction="http://tempuri.org/ITelaColorIntermoda/DeleteResponse")]
        void Delete(int telaColorIntermodaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/Delete", ReplyAction="http://tempuri.org/ITelaColorIntermoda/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int telaColorIntermodaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/Get", ReplyAction="http://tempuri.org/ITelaColorIntermoda/GetResponse")]
        Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness Get(int telaColorIntermodaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/Get", ReplyAction="http://tempuri.org/ITelaColorIntermoda/GetResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness> GetAsync(int telaColorIntermodaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/GetAll", ReplyAction="http://tempuri.org/ITelaColorIntermoda/GetAllResponse")]
        Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/GetAll", ReplyAction="http://tempuri.org/ITelaColorIntermoda/GetAllResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/GetByColorIntermoda", ReplyAction="http://tempuri.org/ITelaColorIntermoda/GetByColorIntermodaResponse")]
        Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness[] GetByColorIntermoda(int colorIntermodaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelaColorIntermoda/GetByColorIntermoda", ReplyAction="http://tempuri.org/ITelaColorIntermoda/GetByColorIntermodaResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness[]> GetByColorIntermodaAsync(int colorIntermodaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITelaColorIntermodaChannel : Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.ITelaColorIntermoda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TelaColorIntermodaClient : System.ServiceModel.ClientBase<Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.ITelaColorIntermoda>, Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.ITelaColorIntermoda {
        
        public TelaColorIntermodaClient() {
        }
        
        public TelaColorIntermodaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TelaColorIntermodaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelaColorIntermodaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelaColorIntermodaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness Update(Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness telaColorIntermoda) {
            return base.Channel.Update(telaColorIntermoda);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness telaColorIntermoda) {
            return base.Channel.UpdateAsync(telaColorIntermoda);
        }
        
        public void Delete(int telaColorIntermodaId) {
            base.Channel.Delete(telaColorIntermodaId);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int telaColorIntermodaId) {
            return base.Channel.DeleteAsync(telaColorIntermodaId);
        }
        
        public Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness Get(int telaColorIntermodaId) {
            return base.Channel.Get(telaColorIntermodaId);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness> GetAsync(int telaColorIntermodaId) {
            return base.Channel.GetAsync(telaColorIntermodaId);
        }
        
        public Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness[] GetByColorIntermoda(int colorIntermodaId) {
            return base.Channel.GetByColorIntermoda(colorIntermodaId);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.TelaColorIntermodaServiceReference.TelaColorIntermodaBusiness[]> GetByColorIntermodaAsync(int colorIntermodaId) {
            return base.Channel.GetByColorIntermodaAsync(colorIntermodaId);
        }
    }
}
