//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaquinaCapacidadBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class MaquinaCapacidadBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CapacidadCanastaLitroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CapacidadMaximaKgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CapacidadMinimaKgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CapacidadCanastaLitro {
            get {
                return this.CapacidadCanastaLitroField;
            }
            set {
                if ((this.CapacidadCanastaLitroField.Equals(value) != true)) {
                    this.CapacidadCanastaLitroField = value;
                    this.RaisePropertyChanged("CapacidadCanastaLitro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CapacidadMaximaKg {
            get {
                return this.CapacidadMaximaKgField;
            }
            set {
                if ((this.CapacidadMaximaKgField.Equals(value) != true)) {
                    this.CapacidadMaximaKgField = value;
                    this.RaisePropertyChanged("CapacidadMaximaKg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CapacidadMinimaKg {
            get {
                return this.CapacidadMinimaKgField;
            }
            set {
                if ((this.CapacidadMinimaKgField.Equals(value) != true)) {
                    this.CapacidadMinimaKgField = value;
                    this.RaisePropertyChanged("CapacidadMinimaKg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaquinaTipo", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Common.Enum")]
    public enum MaquinaTipo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lavadora = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Secadora = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaquinaCapacidadServiceReference.IMaquinaCapacidad")]
    public interface IMaquinaCapacidad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/Update", ReplyAction="http://tempuri.org/IMaquinaCapacidad/UpdateResponse")]
        Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness Update(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness maquinaCapacidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/Update", ReplyAction="http://tempuri.org/IMaquinaCapacidad/UpdateResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness maquinaCapacidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/Delete", ReplyAction="http://tempuri.org/IMaquinaCapacidad/DeleteResponse")]
        void Delete(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo, int maquinaCapacidadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/Delete", ReplyAction="http://tempuri.org/IMaquinaCapacidad/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo, int maquinaCapacidadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/Get", ReplyAction="http://tempuri.org/IMaquinaCapacidad/GetResponse")]
        Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness Get(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo, int maquinaCapacidadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/Get", ReplyAction="http://tempuri.org/IMaquinaCapacidad/GetResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness> GetAsync(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo, int maquinaCapacidadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/GetAll", ReplyAction="http://tempuri.org/IMaquinaCapacidad/GetAllResponse")]
        Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/GetAll", ReplyAction="http://tempuri.org/IMaquinaCapacidad/GetAllResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/GetByTipo", ReplyAction="http://tempuri.org/IMaquinaCapacidad/GetByTipoResponse")]
        Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness[] GetByTipo(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaquinaCapacidad/GetByTipo", ReplyAction="http://tempuri.org/IMaquinaCapacidad/GetByTipoResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness[]> GetByTipoAsync(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaquinaCapacidadChannel : Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.IMaquinaCapacidad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaquinaCapacidadClient : System.ServiceModel.ClientBase<Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.IMaquinaCapacidad>, Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.IMaquinaCapacidad {
        
        public MaquinaCapacidadClient() {
        }
        
        public MaquinaCapacidadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaquinaCapacidadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaquinaCapacidadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaquinaCapacidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness Update(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness maquinaCapacidad) {
            return base.Channel.Update(maquinaCapacidad);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness maquinaCapacidad) {
            return base.Channel.UpdateAsync(maquinaCapacidad);
        }
        
        public void Delete(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo, int maquinaCapacidadId) {
            base.Channel.Delete(tipo, maquinaCapacidadId);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo, int maquinaCapacidadId) {
            return base.Channel.DeleteAsync(tipo, maquinaCapacidadId);
        }
        
        public Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness Get(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo, int maquinaCapacidadId) {
            return base.Channel.Get(tipo, maquinaCapacidadId);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness> GetAsync(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo, int maquinaCapacidadId) {
            return base.Channel.GetAsync(tipo, maquinaCapacidadId);
        }
        
        public Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness[] GetByTipo(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo) {
            return base.Channel.GetByTipo(tipo);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaCapacidadBusiness[]> GetByTipoAsync(Intermoda.ClientProxy.Lavanderia.MaquinaCapacidadServiceReference.MaquinaTipo tipo) {
            return base.Channel.GetByTipoAsync(tipo);
        }
    }
}
