//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.AX.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ax2012R2Entities : DbContext
    {
        public Ax2012R2Entities()
            : base("name=Ax2012R2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INVENTTABLE> INVENTTABLESet { get; set; }
        public virtual DbSet<ECORESPRODUCTTRANSLATION> ECORESPRODUCTTRANSLATIONSet { get; set; }
        public virtual DbSet<ECORESPRODUCT> ECORESPRODUCTSet { get; set; }
        public virtual DbSet<INVENTDIM> INVENTDIMSet { get; set; }
        public virtual DbSet<KANBAN> KANBANSet { get; set; }
        public virtual DbSet<KANBANCARD> KANBANCARDSet { get; set; }
        public virtual DbSet<KANBANJOB> KANBANJOBSet { get; set; }
        public virtual DbSet<KANBANJOBSCHEDULE> KANBANJOBSCHEDULESet { get; set; }
        public virtual DbSet<KANBANRULE> KANBANRULESet { get; set; }
    }
}
