//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.AX.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTDIM
    {
        public string INVENTDIMID { get; set; }
        public string INVENTBATCHID { get; set; }
        public string WMSLOCATIONID { get; set; }
        public string WMSPALLETID { get; set; }
        public string INVENTSERIALID { get; set; }
        public string INVENTLOCATIONID { get; set; }
        public string CONFIGID { get; set; }
        public string INVENTSIZEID { get; set; }
        public string INVENTCOLORID { get; set; }
        public string INVENTSITEID { get; set; }
        public string INVENTGTDID_RU { get; set; }
        public string INVENTPROFILEID_RU { get; set; }
        public string INVENTOWNERID_RU { get; set; }
        public string INVENTSTYLEID { get; set; }
        public byte[] SHA1HASH { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
        public string BFPQUALITYID { get; set; }
        public string BFPPUTUPID { get; set; }
        public string BFPUSERDIM1ID { get; set; }
        public string BFPUSERDIM2ID { get; set; }
    }
}
