//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.AX.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KANBANJOBSCHEDULE
    {
        public System.DateTime PLANNEDPERIOD { get; set; }
        public decimal SEQUENCE { get; set; }
        public long JOB { get; set; }
        public System.DateTime EXPECTEDDATETIME { get; set; }
        public int EXPECTEDDATETIMETZID { get; set; }
        public long WORKCELL { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
