//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.AX.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KANBANJOB
    {
        public long KANBAN { get; set; }
        public string INVENTTRANSID { get; set; }
        public string ISSUEINVENTTRANSID { get; set; }
        public string INVENTDIMID { get; set; }
        public string ISSUEINVENTDIMID { get; set; }
        public int TYPE { get; set; }
        public int STATUS { get; set; }
        public System.DateTime ACTUALSTARTDATETIME { get; set; }
        public int ACTUALSTARTDATETIMETZID { get; set; }
        public System.DateTime ACTUALENDDATETIME { get; set; }
        public int ACTUALENDDATETIMETZID { get; set; }
        public decimal QUANTITYORDERED { get; set; }
        public decimal QUANTITYRECEIVED { get; set; }
        public decimal QUANTITYSCRAPPED { get; set; }
        public System.DateTime EXPECTEDDATETIME { get; set; }
        public int EXPECTEDDATETIMETZID { get; set; }
        public System.DateTime DUEDATETIME { get; set; }
        public int DUEDATETIMETZID { get; set; }
        public string INVENTDIMDATAAREAID { get; set; }
        public string ISSUEINVENTDIMDATAAREAID { get; set; }
        public string INVENTTRANSDATAAREAID { get; set; }
        public string ISSUEINVENTTRANSDATAAREAID { get; set; }
        public string WMSLOCATIONID { get; set; }
        public string INVENTLOCATIONID { get; set; }
        public string INVENTLOCATIONDATAAREAID { get; set; }
        public string WMSLOCATIONDATAAREAID { get; set; }
        public long LEANPRODUCTIONFLOWACTIVITY { get; set; }
        public int EXECUTABLE { get; set; }
        public string LEANSCHEDULEGROUPNAME { get; set; }
        public string LEANSCHEDULEGROUPCOLOR { get; set; }
        public long WORKCELL { get; set; }
        public string PLANACTIVITYNAME { get; set; }
        public long DEFAULTDIMENSION { get; set; }
        public long SOURCEDOCUMENTHEADER { get; set; }
        public int SEQUENCE { get; set; }
        public decimal LEANSCHEDULEITEMRATIO { get; set; }
        public System.DateTime ACTUALPREPAREDDATETIME { get; set; }
        public int ACTUALPREPAREDDATETIMETZID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
        public string APKANBANSENDID { get; set; }
    }
}
