//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenProduccionExternoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.LbDatPro")]
    [System.SerializableAttribute()]
    public partial class OrdenProduccionExternoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.CentroTrabajoBusiness CentroTrabajoSiguienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroTrabajoSiguienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.CentroTrabajoBusiness CentroTrabajoUltimaLecturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroTrabajoUltimaLecturaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CompaniaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenEstadoBusiness EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoLeyendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LavadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdenProduccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.PasoRutaBusiness[] RutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiguienteLecturaTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarianteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((this.AnoField.Equals(value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.CentroTrabajoBusiness CentroTrabajoSiguiente {
            get {
                return this.CentroTrabajoSiguienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoSiguienteField, value) != true)) {
                    this.CentroTrabajoSiguienteField = value;
                    this.RaisePropertyChanged("CentroTrabajoSiguiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroTrabajoSiguienteId {
            get {
                return this.CentroTrabajoSiguienteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoSiguienteIdField, value) != true)) {
                    this.CentroTrabajoSiguienteIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoSiguienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.CentroTrabajoBusiness CentroTrabajoUltimaLectura {
            get {
                return this.CentroTrabajoUltimaLecturaField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoUltimaLecturaField, value) != true)) {
                    this.CentroTrabajoUltimaLecturaField = value;
                    this.RaisePropertyChanged("CentroTrabajoUltimaLectura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroTrabajoUltimaLecturaId {
            get {
                return this.CentroTrabajoUltimaLecturaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoUltimaLecturaIdField, value) != true)) {
                    this.CentroTrabajoUltimaLecturaIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoUltimaLecturaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorDescripcion {
            get {
                return this.ColorDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorDescripcionField, value) != true)) {
                    this.ColorDescripcionField = value;
                    this.RaisePropertyChanged("ColorDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CompaniaId {
            get {
                return this.CompaniaIdField;
            }
            set {
                if ((this.CompaniaIdField.Equals(value) != true)) {
                    this.CompaniaIdField = value;
                    this.RaisePropertyChanged("CompaniaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenEstadoBusiness Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoId {
            get {
                return this.EstadoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoIdField, value) != true)) {
                    this.EstadoIdField = value;
                    this.RaisePropertyChanged("EstadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoLeyenda {
            get {
                return this.EstadoLeyendaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoLeyendaField, value) != true)) {
                    this.EstadoLeyendaField = value;
                    this.RaisePropertyChanged("EstadoLeyenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lavado {
            get {
                return this.LavadoField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoField, value) != true)) {
                    this.LavadoField = value;
                    this.RaisePropertyChanged("Lavado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdenProduccion {
            get {
                return this.OrdenProduccionField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdenProduccionField, value) != true)) {
                    this.OrdenProduccionField = value;
                    this.RaisePropertyChanged("OrdenProduccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patron {
            get {
                return this.PatronField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronField, value) != true)) {
                    this.PatronField = value;
                    this.RaisePropertyChanged("Patron");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.PasoRutaBusiness[] Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiguienteLecturaTipo {
            get {
                return this.SiguienteLecturaTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.SiguienteLecturaTipoField, value) != true)) {
                    this.SiguienteLecturaTipoField = value;
                    this.RaisePropertyChanged("SiguienteLecturaTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tela {
            get {
                return this.TelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaField, value) != true)) {
                    this.TelaField = value;
                    this.RaisePropertyChanged("Tela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variante {
            get {
                return this.VarianteField;
            }
            set {
                if ((object.ReferenceEquals(this.VarianteField, value) != true)) {
                    this.VarianteField = value;
                    this.RaisePropertyChanged("Variante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CentroTrabajoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.LbDatPro")]
    [System.SerializableAttribute()]
    public partial class CentroTrabajoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CompaniaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SecuenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CompaniaId {
            get {
                return this.CompaniaIdField;
            }
            set {
                if ((this.CompaniaIdField.Equals(value) != true)) {
                    this.CompaniaIdField = value;
                    this.RaisePropertyChanged("CompaniaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenEstadoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.LbDatPro")]
    [System.SerializableAttribute()]
    public partial class OrdenEstadoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroCostoAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroTrabajoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> SecuenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroCostoAlias {
            get {
                return this.CentroCostoAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroCostoAliasField, value) != true)) {
                    this.CentroCostoAliasField = value;
                    this.RaisePropertyChanged("CentroCostoAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroTrabajoId {
            get {
                return this.CentroTrabajoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoIdField, value) != true)) {
                    this.CentroTrabajoIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasoRutaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.LbDatPro")]
    [System.SerializableAttribute()]
    public partial class PasoRutaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroTrabajoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CompaniaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LecturaEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LecturaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlantaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlantaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> TiempoEnPlantaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> TiempoEnProcesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((this.AnoField.Equals(value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroTrabajo {
            get {
                return this.CentroTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoField, value) != true)) {
                    this.CentroTrabajoField = value;
                    this.RaisePropertyChanged("CentroTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroTrabajoId {
            get {
                return this.CentroTrabajoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoIdField, value) != true)) {
                    this.CentroTrabajoIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CompaniaId {
            get {
                return this.CompaniaIdField;
            }
            set {
                if ((this.CompaniaIdField.Equals(value) != true)) {
                    this.CompaniaIdField = value;
                    this.RaisePropertyChanged("CompaniaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LecturaEntrada {
            get {
                return this.LecturaEntradaField;
            }
            set {
                if ((this.LecturaEntradaField.Equals(value) != true)) {
                    this.LecturaEntradaField = value;
                    this.RaisePropertyChanged("LecturaEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LecturaSalida {
            get {
                return this.LecturaSalidaField;
            }
            set {
                if ((this.LecturaSalidaField.Equals(value) != true)) {
                    this.LecturaSalidaField = value;
                    this.RaisePropertyChanged("LecturaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Planta {
            get {
                return this.PlantaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantaField, value) != true)) {
                    this.PlantaField = value;
                    this.RaisePropertyChanged("Planta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantaId {
            get {
                return this.PlantaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantaIdField, value) != true)) {
                    this.PlantaIdField = value;
                    this.RaisePropertyChanged("PlantaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TiempoEnPlanta {
            get {
                return this.TiempoEnPlantaField;
            }
            set {
                if ((this.TiempoEnPlantaField.Equals(value) != true)) {
                    this.TiempoEnPlantaField = value;
                    this.RaisePropertyChanged("TiempoEnPlanta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TiempoEnProceso {
            get {
                return this.TiempoEnProcesoField;
            }
            set {
                if ((this.TiempoEnProcesoField.Equals(value) != true)) {
                    this.TiempoEnProcesoField = value;
                    this.RaisePropertyChanged("TiempoEnProceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaquiladoTrabajoEnProceso", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.LbDatPro")]
    [System.SerializableAttribute()]
    public partial class MaquiladoTrabajoEnProceso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.CentroTrabajoBusiness CentroTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LavadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrdenAnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrdenNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.PlantaBusiness PlantaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TiempoPlantaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TiempoProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarianteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.CentroTrabajoBusiness CentroTrabajo {
            get {
                return this.CentroTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoField, value) != true)) {
                    this.CentroTrabajoField = value;
                    this.RaisePropertyChanged("CentroTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorNombre {
            get {
                return this.ColorNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorNombreField, value) != true)) {
                    this.ColorNombreField = value;
                    this.RaisePropertyChanged("ColorNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Entrada {
            get {
                return this.EntradaField;
            }
            set {
                if ((this.EntradaField.Equals(value) != true)) {
                    this.EntradaField = value;
                    this.RaisePropertyChanged("Entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lavado {
            get {
                return this.LavadoField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoField, value) != true)) {
                    this.LavadoField = value;
                    this.RaisePropertyChanged("Lavado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OrdenAno {
            get {
                return this.OrdenAnoField;
            }
            set {
                if ((this.OrdenAnoField.Equals(value) != true)) {
                    this.OrdenAnoField = value;
                    this.RaisePropertyChanged("OrdenAno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OrdenNumero {
            get {
                return this.OrdenNumeroField;
            }
            set {
                if ((this.OrdenNumeroField.Equals(value) != true)) {
                    this.OrdenNumeroField = value;
                    this.RaisePropertyChanged("OrdenNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patron {
            get {
                return this.PatronField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronField, value) != true)) {
                    this.PatronField = value;
                    this.RaisePropertyChanged("Patron");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.PlantaBusiness Planta {
            get {
                return this.PlantaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantaField, value) != true)) {
                    this.PlantaField = value;
                    this.RaisePropertyChanged("Planta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Salida {
            get {
                return this.SalidaField;
            }
            set {
                if ((this.SalidaField.Equals(value) != true)) {
                    this.SalidaField = value;
                    this.RaisePropertyChanged("Salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tela {
            get {
                return this.TelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaField, value) != true)) {
                    this.TelaField = value;
                    this.RaisePropertyChanged("Tela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TiempoPlanta {
            get {
                return this.TiempoPlantaField;
            }
            set {
                if ((this.TiempoPlantaField.Equals(value) != true)) {
                    this.TiempoPlantaField = value;
                    this.RaisePropertyChanged("TiempoPlanta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TiempoProceso {
            get {
                return this.TiempoProcesoField;
            }
            set {
                if ((this.TiempoProcesoField.Equals(value) != true)) {
                    this.TiempoProcesoField = value;
                    this.RaisePropertyChanged("TiempoProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variante {
            get {
                return this.VarianteField;
            }
            set {
                if ((object.ReferenceEquals(this.VarianteField, value) != true)) {
                    this.VarianteField = value;
                    this.RaisePropertyChanged("Variante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlantaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.LbDatPro")]
    [System.SerializableAttribute()]
    public partial class PlantaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> BodegaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> CompaniaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneraTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> HabilitarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InicialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NuevoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> ProveedorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProveedorNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> BodegaId {
            get {
                return this.BodegaIdField;
            }
            set {
                if ((this.BodegaIdField.Equals(value) != true)) {
                    this.BodegaIdField = value;
                    this.RaisePropertyChanged("BodegaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> CompaniaId {
            get {
                return this.CompaniaIdField;
            }
            set {
                if ((this.CompaniaIdField.Equals(value) != true)) {
                    this.CompaniaIdField = value;
                    this.RaisePropertyChanged("CompaniaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneraTicket {
            get {
                return this.GeneraTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneraTicketField, value) != true)) {
                    this.GeneraTicketField = value;
                    this.RaisePropertyChanged("GeneraTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Habilitar {
            get {
                return this.HabilitarField;
            }
            set {
                if ((this.HabilitarField.Equals(value) != true)) {
                    this.HabilitarField = value;
                    this.RaisePropertyChanged("Habilitar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iniciales {
            get {
                return this.InicialesField;
            }
            set {
                if ((object.ReferenceEquals(this.InicialesField, value) != true)) {
                    this.InicialesField = value;
                    this.RaisePropertyChanged("Iniciales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NuevoId {
            get {
                return this.NuevoIdField;
            }
            set {
                if ((this.NuevoIdField.Equals(value) != true)) {
                    this.NuevoIdField = value;
                    this.RaisePropertyChanged("NuevoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ProveedorId {
            get {
                return this.ProveedorIdField;
            }
            set {
                if ((this.ProveedorIdField.Equals(value) != true)) {
                    this.ProveedorIdField = value;
                    this.RaisePropertyChanged("ProveedorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProveedorNombre {
            get {
                return this.ProveedorNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorNombreField, value) != true)) {
                    this.ProveedorNombreField = value;
                    this.RaisePropertyChanged("ProveedorNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdenProduccionExternoServiceReference.IOrdenProduccionExterno")]
    public interface IOrdenProduccionExterno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/GetByUsuarioPlanta", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/GetByUsuarioPlantaResponse")]
        Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness[] GetByUsuarioPlanta(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/GetByUsuarioPlanta", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/GetByUsuarioPlantaResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness[]> GetByUsuarioPlantaAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/Get", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/GetResponse")]
        Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/Get", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/GetResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/GetMaquiladoTrabajoEnProceso", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/GetMaquiladoTrabajoEnProcesoResponse")]
        Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.MaquiladoTrabajoEnProceso[] GetMaquiladoTrabajoEnProceso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/GetMaquiladoTrabajoEnProceso", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/GetMaquiladoTrabajoEnProcesoResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.MaquiladoTrabajoEnProceso[]> GetMaquiladoTrabajoEnProcesoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/SetEstado", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/SetEstadoResponse")]
        void SetEstado(short companiaId, short ordenAno, short ordenNumero, string estadoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/SetEstado", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/SetEstadoResponse")]
        System.Threading.Tasks.Task SetEstadoAsync(short companiaId, short ordenAno, short ordenNumero, string estadoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/GrabarLectura", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/GrabarLecturaResponse")]
        Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness GrabarLectura(short companiaId, short ordenAno, short ordenNumero, string centroTrabajoId, string tipo, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/GrabarLectura", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/GrabarLecturaResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness> GrabarLecturaAsync(short companiaId, short ordenAno, short ordenNumero, string centroTrabajoId, string tipo, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/SetEstadoEnviarIntermoda", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/SetEstadoEnviarIntermodaResponse")]
        void SetEstadoEnviarIntermoda(short companiaId, short ordenAno, short ordenNumero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenProduccionExterno/SetEstadoEnviarIntermoda", ReplyAction="http://tempuri.org/IOrdenProduccionExterno/SetEstadoEnviarIntermodaResponse")]
        System.Threading.Tasks.Task SetEstadoEnviarIntermodaAsync(short companiaId, short ordenAno, short ordenNumero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenProduccionExternoChannel : Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.IOrdenProduccionExterno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenProduccionExternoClient : System.ServiceModel.ClientBase<Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.IOrdenProduccionExterno>, Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.IOrdenProduccionExterno {
        
        public OrdenProduccionExternoClient() {
        }
        
        public OrdenProduccionExternoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenProduccionExternoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenProduccionExternoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenProduccionExternoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness[] GetByUsuarioPlanta(string usuario) {
            return base.Channel.GetByUsuarioPlanta(usuario);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness[]> GetByUsuarioPlantaAsync(string usuario) {
            return base.Channel.GetByUsuarioPlantaAsync(usuario);
        }
        
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.MaquiladoTrabajoEnProceso[] GetMaquiladoTrabajoEnProceso() {
            return base.Channel.GetMaquiladoTrabajoEnProceso();
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.MaquiladoTrabajoEnProceso[]> GetMaquiladoTrabajoEnProcesoAsync() {
            return base.Channel.GetMaquiladoTrabajoEnProcesoAsync();
        }
        
        public void SetEstado(short companiaId, short ordenAno, short ordenNumero, string estadoId) {
            base.Channel.SetEstado(companiaId, ordenAno, ordenNumero, estadoId);
        }
        
        public System.Threading.Tasks.Task SetEstadoAsync(short companiaId, short ordenAno, short ordenNumero, string estadoId) {
            return base.Channel.SetEstadoAsync(companiaId, ordenAno, ordenNumero, estadoId);
        }
        
        public Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness GrabarLectura(short companiaId, short ordenAno, short ordenNumero, string centroTrabajoId, string tipo, string usuario) {
            return base.Channel.GrabarLectura(companiaId, ordenAno, ordenNumero, centroTrabajoId, tipo, usuario);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.LbDatPro.OrdenProduccionExternoServiceReference.OrdenProduccionExternoBusiness> GrabarLecturaAsync(short companiaId, short ordenAno, short ordenNumero, string centroTrabajoId, string tipo, string usuario) {
            return base.Channel.GrabarLecturaAsync(companiaId, ordenAno, ordenNumero, centroTrabajoId, tipo, usuario);
        }
        
        public void SetEstadoEnviarIntermoda(short companiaId, short ordenAno, short ordenNumero) {
            base.Channel.SetEstadoEnviarIntermoda(companiaId, ordenAno, ordenNumero);
        }
        
        public System.Threading.Tasks.Task SetEstadoEnviarIntermodaAsync(short companiaId, short ordenAno, short ordenNumero) {
            return base.Channel.SetEstadoEnviarIntermodaAsync(companiaId, ordenAno, ordenNumero);
        }
    }
}
