//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CentroTrabajoOpcionBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class CentroTrabajoOpcionBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CTrabajoBusiness CentroTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CentroTrabajoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroTrabajoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroTrabajoObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpcionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.OpcionLavadoBusiness OpcionLavadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CTrabajoBusiness CentroTrabajo {
            get {
                return this.CentroTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoField, value) != true)) {
                    this.CentroTrabajoField = value;
                    this.RaisePropertyChanged("CentroTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CentroTrabajoId {
            get {
                return this.CentroTrabajoIdField;
            }
            set {
                if ((this.CentroTrabajoIdField.Equals(value) != true)) {
                    this.CentroTrabajoIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroTrabajoNombre {
            get {
                return this.CentroTrabajoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoNombreField, value) != true)) {
                    this.CentroTrabajoNombreField = value;
                    this.RaisePropertyChanged("CentroTrabajoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroTrabajoObservacion {
            get {
                return this.CentroTrabajoObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoObservacionField, value) != true)) {
                    this.CentroTrabajoObservacionField = value;
                    this.RaisePropertyChanged("CentroTrabajoObservacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpcionId {
            get {
                return this.OpcionIdField;
            }
            set {
                if ((this.OpcionIdField.Equals(value) != true)) {
                    this.OpcionIdField = value;
                    this.RaisePropertyChanged("OpcionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.OpcionLavadoBusiness OpcionLavado {
            get {
                return this.OpcionLavadoField;
            }
            set {
                if ((object.ReferenceEquals(this.OpcionLavadoField, value) != true)) {
                    this.OpcionLavadoField = value;
                    this.RaisePropertyChanged("OpcionLavado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTrabajoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class CTrabajoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EsActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EsObligatorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LineaProduccionCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TiempoEsperaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TiempoProcesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EsActivo {
            get {
                return this.EsActivoField;
            }
            set {
                if ((this.EsActivoField.Equals(value) != true)) {
                    this.EsActivoField = value;
                    this.RaisePropertyChanged("EsActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EsObligatorio {
            get {
                return this.EsObligatorioField;
            }
            set {
                if ((this.EsObligatorioField.Equals(value) != true)) {
                    this.EsObligatorioField = value;
                    this.RaisePropertyChanged("EsObligatorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LineaProduccionCodigo {
            get {
                return this.LineaProduccionCodigoField;
            }
            set {
                if ((this.LineaProduccionCodigoField.Equals(value) != true)) {
                    this.LineaProduccionCodigoField = value;
                    this.RaisePropertyChanged("LineaProduccionCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TiempoEspera {
            get {
                return this.TiempoEsperaField;
            }
            set {
                if ((this.TiempoEsperaField.Equals(value) != true)) {
                    this.TiempoEsperaField = value;
                    this.RaisePropertyChanged("TiempoEspera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TiempoProceso {
            get {
                return this.TiempoProcesoField;
            }
            set {
                if ((this.TiempoProcesoField.Equals(value) != true)) {
                    this.TiempoProcesoField = value;
                    this.RaisePropertyChanged("TiempoProceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpcionLavadoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class OpcionLavadoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.LavadoBusiness LavadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LavadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.TelaBusiness TelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.LavadoBusiness Lavado {
            get {
                return this.LavadoField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoField, value) != true)) {
                    this.LavadoField = value;
                    this.RaisePropertyChanged("Lavado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LavadoId {
            get {
                return this.LavadoIdField;
            }
            set {
                if ((this.LavadoIdField.Equals(value) != true)) {
                    this.LavadoIdField = value;
                    this.RaisePropertyChanged("LavadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.TelaBusiness Tela {
            get {
                return this.TelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaField, value) != true)) {
                    this.TelaField = value;
                    this.RaisePropertyChanged("Tela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaId {
            get {
                return this.TelaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaIdField, value) != true)) {
                    this.TelaIdField = value;
                    this.RaisePropertyChanged("TelaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LavadoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class LavadoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.ColoresIntermodaBusiness ColorIntermodaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LavadoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LavadoFechaActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LavadoFechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LavadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LavadoNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColorId {
            get {
                return this.ColorIdField;
            }
            set {
                if ((this.ColorIdField.Equals(value) != true)) {
                    this.ColorIdField = value;
                    this.RaisePropertyChanged("ColorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.ColoresIntermodaBusiness ColorIntermoda {
            get {
                return this.ColorIntermodaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorIntermodaField, value) != true)) {
                    this.ColorIntermodaField = value;
                    this.RaisePropertyChanged("ColorIntermoda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsActivo {
            get {
                return this.IsActivoField;
            }
            set {
                if ((this.IsActivoField.Equals(value) != true)) {
                    this.IsActivoField = value;
                    this.RaisePropertyChanged("IsActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LavadoDescripcion {
            get {
                return this.LavadoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoDescripcionField, value) != true)) {
                    this.LavadoDescripcionField = value;
                    this.RaisePropertyChanged("LavadoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LavadoFechaActualizacion {
            get {
                return this.LavadoFechaActualizacionField;
            }
            set {
                if ((this.LavadoFechaActualizacionField.Equals(value) != true)) {
                    this.LavadoFechaActualizacionField = value;
                    this.RaisePropertyChanged("LavadoFechaActualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LavadoFechaCreacion {
            get {
                return this.LavadoFechaCreacionField;
            }
            set {
                if ((this.LavadoFechaCreacionField.Equals(value) != true)) {
                    this.LavadoFechaCreacionField = value;
                    this.RaisePropertyChanged("LavadoFechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LavadoId {
            get {
                return this.LavadoIdField;
            }
            set {
                if ((this.LavadoIdField.Equals(value) != true)) {
                    this.LavadoIdField = value;
                    this.RaisePropertyChanged("LavadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LavadoNombre {
            get {
                return this.LavadoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoNombreField, value) != true)) {
                    this.LavadoNombreField = value;
                    this.RaisePropertyChanged("LavadoNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class TelaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComposicionNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaterialCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComposicionNombre {
            get {
                return this.ComposicionNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ComposicionNombreField, value) != true)) {
                    this.ComposicionNombreField = value;
                    this.RaisePropertyChanged("ComposicionNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaterialCodigo {
            get {
                return this.MaterialCodigoField;
            }
            set {
                if ((this.MaterialCodigoField.Equals(value) != true)) {
                    this.MaterialCodigoField = value;
                    this.RaisePropertyChanged("MaterialCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaCodigo {
            get {
                return this.TelaCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaCodigoField, value) != true)) {
                    this.TelaCodigoField = value;
                    this.RaisePropertyChanged("TelaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaDescripcion {
            get {
                return this.TelaDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaDescripcionField, value) != true)) {
                    this.TelaDescripcionField = value;
                    this.RaisePropertyChanged("TelaDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaNombre {
            get {
                return this.TelaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaNombreField, value) != true)) {
                    this.TelaNombreField = value;
                    this.RaisePropertyChanged("TelaNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColoresIntermodaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class ColoresIntermodaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CentroTrabajoOpcionServiceReference.ICentroTrabajoOpcion")]
    public interface ICentroTrabajoOpcion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/Update", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/UpdateResponse")]
        Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness Update(Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness centroTrabajoOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/Update", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/UpdateResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness centroTrabajoOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/InsertLegacy", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/InsertLegacyResponse")]
        void InsertLegacy(int opcionId, int centroTrabajoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/InsertLegacy", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/InsertLegacyResponse")]
        System.Threading.Tasks.Task InsertLegacyAsync(int opcionId, int centroTrabajoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/BajarOrden", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/BajarOrdenResponse")]
        void BajarOrden(int centroTrabajoOpcionId, int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/BajarOrden", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/BajarOrdenResponse")]
        System.Threading.Tasks.Task BajarOrdenAsync(int centroTrabajoOpcionId, int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/SubirOrden", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/SubirOrdenResponse")]
        void SubirOrden(int centroTrabajoOpcionId, int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/SubirOrden", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/SubirOrdenResponse")]
        System.Threading.Tasks.Task SubirOrdenAsync(int centroTrabajoOpcionId, int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/Delete", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/DeleteResponse")]
        void Delete(int centroTrabajoOpcionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/Delete", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int centroTrabajoOpcionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/DeleteRutaOpcionAcabado", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/DeleteRutaOpcionAcabadoResponse")]
        void DeleteRutaOpcionAcabado(int opcionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/DeleteRutaOpcionAcabado", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/DeleteRutaOpcionAcabadoResponse")]
        System.Threading.Tasks.Task DeleteRutaOpcionAcabadoAsync(int opcionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/Get", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/GetResponse")]
        Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness Get(int centroTrabajoOpcionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/Get", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/GetResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness> GetAsync(int centroTrabajoOpcionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/GetAll", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/GetAllResponse")]
        Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/GetAll", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/GetAllResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/GetByOpcion", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/GetByOpcionResponse")]
        Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[] GetByOpcion(int opcionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/GetByOpcion", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/GetByOpcionResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[]> GetByOpcionAsync(int opcionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/GetByCentroTrabajo", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/GetByCentroTrabajoResponse")]
        Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[] GetByCentroTrabajo(int centroTrabajoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroTrabajoOpcion/GetByCentroTrabajo", ReplyAction="http://tempuri.org/ICentroTrabajoOpcion/GetByCentroTrabajoResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[]> GetByCentroTrabajoAsync(int centroTrabajoId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentroTrabajoOpcionChannel : Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.ICentroTrabajoOpcion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentroTrabajoOpcionClient : System.ServiceModel.ClientBase<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.ICentroTrabajoOpcion>, Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.ICentroTrabajoOpcion {
        
        public CentroTrabajoOpcionClient() {
        }
        
        public CentroTrabajoOpcionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CentroTrabajoOpcionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentroTrabajoOpcionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentroTrabajoOpcionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness Update(Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness centroTrabajoOpcion) {
            return base.Channel.Update(centroTrabajoOpcion);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness centroTrabajoOpcion) {
            return base.Channel.UpdateAsync(centroTrabajoOpcion);
        }
        
        public void InsertLegacy(int opcionId, int centroTrabajoId) {
            base.Channel.InsertLegacy(opcionId, centroTrabajoId);
        }
        
        public System.Threading.Tasks.Task InsertLegacyAsync(int opcionId, int centroTrabajoId) {
            return base.Channel.InsertLegacyAsync(opcionId, centroTrabajoId);
        }
        
        public void BajarOrden(int centroTrabajoOpcionId, int orden) {
            base.Channel.BajarOrden(centroTrabajoOpcionId, orden);
        }
        
        public System.Threading.Tasks.Task BajarOrdenAsync(int centroTrabajoOpcionId, int orden) {
            return base.Channel.BajarOrdenAsync(centroTrabajoOpcionId, orden);
        }
        
        public void SubirOrden(int centroTrabajoOpcionId, int orden) {
            base.Channel.SubirOrden(centroTrabajoOpcionId, orden);
        }
        
        public System.Threading.Tasks.Task SubirOrdenAsync(int centroTrabajoOpcionId, int orden) {
            return base.Channel.SubirOrdenAsync(centroTrabajoOpcionId, orden);
        }
        
        public void Delete(int centroTrabajoOpcionId) {
            base.Channel.Delete(centroTrabajoOpcionId);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int centroTrabajoOpcionId) {
            return base.Channel.DeleteAsync(centroTrabajoOpcionId);
        }
        
        public void DeleteRutaOpcionAcabado(int opcionId) {
            base.Channel.DeleteRutaOpcionAcabado(opcionId);
        }
        
        public System.Threading.Tasks.Task DeleteRutaOpcionAcabadoAsync(int opcionId) {
            return base.Channel.DeleteRutaOpcionAcabadoAsync(opcionId);
        }
        
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness Get(int centroTrabajoOpcionId) {
            return base.Channel.Get(centroTrabajoOpcionId);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness> GetAsync(int centroTrabajoOpcionId) {
            return base.Channel.GetAsync(centroTrabajoOpcionId);
        }
        
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[] GetByOpcion(int opcionId) {
            return base.Channel.GetByOpcion(opcionId);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[]> GetByOpcionAsync(int opcionId) {
            return base.Channel.GetByOpcionAsync(opcionId);
        }
        
        public Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[] GetByCentroTrabajo(int centroTrabajoId) {
            return base.Channel.GetByCentroTrabajo(centroTrabajoId);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.CentroTrabajoOpcionServiceReference.CentroTrabajoOpcionBusiness[]> GetByCentroTrabajoAsync(int centroTrabajoId) {
            return base.Channel.GetByCentroTrabajoAsync(centroTrabajoId);
        }
    }
}
