//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lecturas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroTrabajoClasificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentroTrabajoClasificacion()
        {
            this.ModuloSemanaOperario = new HashSet<ModuloSemanaOperario>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int Secuencia { get; set; }
        public int Tipo { get; set; }
        public int CentroTrabajoId { get; set; }
        public bool Estado { get; set; }
    
        public virtual CentroTrabajo CentroTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuloSemanaOperario> ModuloSemanaOperario { get; set; }
    }
}
