//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lecturas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JornadaDetalle
    {
        public int Id { get; set; }
        public int JornadaId { get; set; }
        public int EntradaHora { get; set; }
        public int EntradaMinuto { get; set; }
        public int SalidaHora { get; set; }
        public int SalidaMinuto { get; set; }
        public int Horas { get; set; }
        public int Minutos { get; set; }
    
        public virtual Jornada Jornada { get; set; }
    }
}
