//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lecturas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloSemana
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuloSemana()
        {
            this.ModuloSemanaOperario = new HashSet<ModuloSemanaOperario>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public int CentroTrabajoId { get; set; }
        public int ModuloId { get; set; }
        public int TransferenciaMinutos { get; set; }
        public int MetaPiezasPorHora { get; set; }
        public decimal MetaProduccion { get; set; }
        public decimal Curva { get; set; }
        public int MinutosEntrenamiento { get; set; }
        public int MinutosTitular { get; set; }
        public int MinutosUtilitario { get; set; }
        public int MinutosBase { get; set; }
        public int TurnoId { get; set; }
    
        public virtual CentroTrabajo CentroTrabajo { get; set; }
        public virtual Modulo Modulo { get; set; }
        public virtual Turno Turno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuloSemanaOperario> ModuloSemanaOperario { get; set; }
    }
}
