//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.LbDatPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUTARC1
    {
        public short CIACOD { get; set; }
        public short PrdNumCor { get; set; }
        public short PrdAnoCor { get; set; }
        public short PrdNoBund { get; set; }
        public Nullable<short> PrdUniPri { get; set; }
        public string PrdBulto { get; set; }
        public Nullable<short> PrdUniSeg { get; set; }
        public Nullable<short> PrdUniTer { get; set; }
        public Nullable<short> PrdUniPer { get; set; }
        public Nullable<short> PrdUniEli { get; set; }
        public string PrdPtoReo { get; set; }
        public Nullable<short> PrdIniCap { get; set; }
        public Nullable<short> PrdFinCap { get; set; }
        public string FacCTall { get; set; }
        public Nullable<short> FacCTallN { get; set; }
        public Nullable<short> PrdCodDim { get; set; }
        public Nullable<short> PrdCanBun { get; set; }
        public Nullable<short> PrdSeccion { get; set; }
        public Nullable<short> PrdTroco { get; set; }
        public Nullable<short> PrdCanTro { get; set; }
    }
}
