//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.LbDatPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACCOL
    {
        public short CIACOD { get; set; }
        public string FacCCol { get; set; }
        public string FacDCol { get; set; }
        public string FacIDCol { get; set; }
        public string AxColorId01 { get; set; }
    }
}
