//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.LbDatPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATMST1
    {
        public short CIACOD { get; set; }
        public int MapCodMat { get; set; }
        public short MprCodBod { get; set; }
        public Nullable<decimal> MprExiBod { get; set; }
        public Nullable<decimal> MprBodCos { get; set; }
        public Nullable<decimal> MprExiMax { get; set; }
        public Nullable<decimal> MPrExiReo { get; set; }
        public Nullable<decimal> MprExiMin { get; set; }
        public Nullable<short> MprExiSts { get; set; }
    }
}
