//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.LbDatPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRCOLOR
    {
        public short CiaCod { get; set; }
        public string MprCodCol { get; set; }
        public string MprDesCol { get; set; }
        public string MprColAX { get; set; }
    }
}
