//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObservacionOperacionBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class ObservacionOperacionBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OperacionProcesoBusiness OperacionProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperacionProcesoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PosicionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OperacionProcesoBusiness OperacionProceso {
            get {
                return this.OperacionProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionProcesoField, value) != true)) {
                    this.OperacionProcesoField = value;
                    this.RaisePropertyChanged("OperacionProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperacionProcesoId {
            get {
                return this.OperacionProcesoIdField;
            }
            set {
                if ((this.OperacionProcesoIdField.Equals(value) != true)) {
                    this.OperacionProcesoIdField = value;
                    this.RaisePropertyChanged("OperacionProcesoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((this.PosicionField.Equals(value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionProcesoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class OperacionProcesoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OperacionBusiness OperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperacionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ProcesoBusiness ProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ProcesoCentroTrabajoBusiness ProcesoCentroTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcesoCentroTrabajoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcesoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RelacionBanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemperaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TiempoEstandarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TiempoMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TiempoMinimoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OperacionBusiness Operacion {
            get {
                return this.OperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionField, value) != true)) {
                    this.OperacionField = value;
                    this.RaisePropertyChanged("Operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperacionId {
            get {
                return this.OperacionIdField;
            }
            set {
                if ((this.OperacionIdField.Equals(value) != true)) {
                    this.OperacionIdField = value;
                    this.RaisePropertyChanged("OperacionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ph {
            get {
                return this.PhField;
            }
            set {
                if ((object.ReferenceEquals(this.PhField, value) != true)) {
                    this.PhField = value;
                    this.RaisePropertyChanged("Ph");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ProcesoBusiness Proceso {
            get {
                return this.ProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcesoField, value) != true)) {
                    this.ProcesoField = value;
                    this.RaisePropertyChanged("Proceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ProcesoCentroTrabajoBusiness ProcesoCentroTrabajo {
            get {
                return this.ProcesoCentroTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcesoCentroTrabajoField, value) != true)) {
                    this.ProcesoCentroTrabajoField = value;
                    this.RaisePropertyChanged("ProcesoCentroTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcesoCentroTrabajoId {
            get {
                return this.ProcesoCentroTrabajoIdField;
            }
            set {
                if ((this.ProcesoCentroTrabajoIdField.Equals(value) != true)) {
                    this.ProcesoCentroTrabajoIdField = value;
                    this.RaisePropertyChanged("ProcesoCentroTrabajoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcesoId {
            get {
                return this.ProcesoIdField;
            }
            set {
                if ((this.ProcesoIdField.Equals(value) != true)) {
                    this.ProcesoIdField = value;
                    this.RaisePropertyChanged("ProcesoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RelacionBano {
            get {
                return this.RelacionBanoField;
            }
            set {
                if ((this.RelacionBanoField.Equals(value) != true)) {
                    this.RelacionBanoField = value;
                    this.RaisePropertyChanged("RelacionBano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Temperatura {
            get {
                return this.TemperaturaField;
            }
            set {
                if ((this.TemperaturaField.Equals(value) != true)) {
                    this.TemperaturaField = value;
                    this.RaisePropertyChanged("Temperatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TiempoEstandar {
            get {
                return this.TiempoEstandarField;
            }
            set {
                if ((this.TiempoEstandarField.Equals(value) != true)) {
                    this.TiempoEstandarField = value;
                    this.RaisePropertyChanged("TiempoEstandar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TiempoMaximo {
            get {
                return this.TiempoMaximoField;
            }
            set {
                if ((this.TiempoMaximoField.Equals(value) != true)) {
                    this.TiempoMaximoField = value;
                    this.RaisePropertyChanged("TiempoMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TiempoMinimo {
            get {
                return this.TiempoMinimoField;
            }
            set {
                if ((this.TiempoMinimoField.Equals(value) != true)) {
                    this.TiempoMinimoField = value;
                    this.RaisePropertyChanged("TiempoMinimo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class OperacionBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short GrupoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineaProduccionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OperacionPredefinidaBusiness OperacionPredefinidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OperacionTipoIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short GrupoId {
            get {
                return this.GrupoIdField;
            }
            set {
                if ((this.GrupoIdField.Equals(value) != true)) {
                    this.GrupoIdField = value;
                    this.RaisePropertyChanged("GrupoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineaProduccionId {
            get {
                return this.LineaProduccionIdField;
            }
            set {
                if ((this.LineaProduccionIdField.Equals(value) != true)) {
                    this.LineaProduccionIdField = value;
                    this.RaisePropertyChanged("LineaProduccionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OperacionPredefinidaBusiness OperacionPredefinida {
            get {
                return this.OperacionPredefinidaField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionPredefinidaField, value) != true)) {
                    this.OperacionPredefinidaField = value;
                    this.RaisePropertyChanged("OperacionPredefinida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OperacionTipoId {
            get {
                return this.OperacionTipoIdField;
            }
            set {
                if ((this.OperacionTipoIdField.Equals(value) != true)) {
                    this.OperacionTipoIdField = value;
                    this.RaisePropertyChanged("OperacionTipoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcesoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class ProcesoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.CTrabajoBusiness CentroTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CentroTrabajoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsObligatorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TiempoEstandarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.CTrabajoBusiness CentroTrabajo {
            get {
                return this.CentroTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoField, value) != true)) {
                    this.CentroTrabajoField = value;
                    this.RaisePropertyChanged("CentroTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CentroTrabajoId {
            get {
                return this.CentroTrabajoIdField;
            }
            set {
                if ((this.CentroTrabajoIdField.Equals(value) != true)) {
                    this.CentroTrabajoIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsActivo {
            get {
                return this.EsActivoField;
            }
            set {
                if ((this.EsActivoField.Equals(value) != true)) {
                    this.EsActivoField = value;
                    this.RaisePropertyChanged("EsActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsObligatorio {
            get {
                return this.EsObligatorioField;
            }
            set {
                if ((this.EsObligatorioField.Equals(value) != true)) {
                    this.EsObligatorioField = value;
                    this.RaisePropertyChanged("EsObligatorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TiempoEstandar {
            get {
                return this.TiempoEstandarField;
            }
            set {
                if ((this.TiempoEstandarField.Equals(value) != true)) {
                    this.TiempoEstandarField = value;
                    this.RaisePropertyChanged("TiempoEstandar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcesoCentroTrabajoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class ProcesoCentroTrabajoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.CTrabajoBusiness CentroTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CentroTrabajoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.CentroTrabajoOpcionBusiness CentroTrabajoOpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CentroTrabajoOpcionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ProcesoBusiness ProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcesoIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.CTrabajoBusiness CentroTrabajo {
            get {
                return this.CentroTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoField, value) != true)) {
                    this.CentroTrabajoField = value;
                    this.RaisePropertyChanged("CentroTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CentroTrabajoId {
            get {
                return this.CentroTrabajoIdField;
            }
            set {
                if ((this.CentroTrabajoIdField.Equals(value) != true)) {
                    this.CentroTrabajoIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.CentroTrabajoOpcionBusiness CentroTrabajoOpcion {
            get {
                return this.CentroTrabajoOpcionField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoOpcionField, value) != true)) {
                    this.CentroTrabajoOpcionField = value;
                    this.RaisePropertyChanged("CentroTrabajoOpcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CentroTrabajoOpcionId {
            get {
                return this.CentroTrabajoOpcionIdField;
            }
            set {
                if ((this.CentroTrabajoOpcionIdField.Equals(value) != true)) {
                    this.CentroTrabajoOpcionIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoOpcionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ProcesoBusiness Proceso {
            get {
                return this.ProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcesoField, value) != true)) {
                    this.ProcesoField = value;
                    this.RaisePropertyChanged("Proceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcesoId {
            get {
                return this.ProcesoIdField;
            }
            set {
                if ((this.ProcesoIdField.Equals(value) != true)) {
                    this.ProcesoIdField = value;
                    this.RaisePropertyChanged("ProcesoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionPredefinidaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class OperacionPredefinidaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OperacionBusiness OperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperacionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RelacionBanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemperaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TiempoMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TiempoMinimoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OperacionBusiness Operacion {
            get {
                return this.OperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionField, value) != true)) {
                    this.OperacionField = value;
                    this.RaisePropertyChanged("Operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperacionId {
            get {
                return this.OperacionIdField;
            }
            set {
                if ((this.OperacionIdField.Equals(value) != true)) {
                    this.OperacionIdField = value;
                    this.RaisePropertyChanged("OperacionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ph {
            get {
                return this.PhField;
            }
            set {
                if ((object.ReferenceEquals(this.PhField, value) != true)) {
                    this.PhField = value;
                    this.RaisePropertyChanged("Ph");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RelacionBano {
            get {
                return this.RelacionBanoField;
            }
            set {
                if ((this.RelacionBanoField.Equals(value) != true)) {
                    this.RelacionBanoField = value;
                    this.RaisePropertyChanged("RelacionBano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Temperatura {
            get {
                return this.TemperaturaField;
            }
            set {
                if ((this.TemperaturaField.Equals(value) != true)) {
                    this.TemperaturaField = value;
                    this.RaisePropertyChanged("Temperatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TiempoMaximo {
            get {
                return this.TiempoMaximoField;
            }
            set {
                if ((this.TiempoMaximoField.Equals(value) != true)) {
                    this.TiempoMaximoField = value;
                    this.RaisePropertyChanged("TiempoMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TiempoMinimo {
            get {
                return this.TiempoMinimoField;
            }
            set {
                if ((this.TiempoMinimoField.Equals(value) != true)) {
                    this.TiempoMinimoField = value;
                    this.RaisePropertyChanged("TiempoMinimo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTrabajoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class CTrabajoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EsActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EsObligatorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LineaProduccionCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TiempoEsperaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TiempoProcesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EsActivo {
            get {
                return this.EsActivoField;
            }
            set {
                if ((this.EsActivoField.Equals(value) != true)) {
                    this.EsActivoField = value;
                    this.RaisePropertyChanged("EsActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EsObligatorio {
            get {
                return this.EsObligatorioField;
            }
            set {
                if ((this.EsObligatorioField.Equals(value) != true)) {
                    this.EsObligatorioField = value;
                    this.RaisePropertyChanged("EsObligatorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LineaProduccionCodigo {
            get {
                return this.LineaProduccionCodigoField;
            }
            set {
                if ((this.LineaProduccionCodigoField.Equals(value) != true)) {
                    this.LineaProduccionCodigoField = value;
                    this.RaisePropertyChanged("LineaProduccionCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TiempoEspera {
            get {
                return this.TiempoEsperaField;
            }
            set {
                if ((this.TiempoEsperaField.Equals(value) != true)) {
                    this.TiempoEsperaField = value;
                    this.RaisePropertyChanged("TiempoEspera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TiempoProceso {
            get {
                return this.TiempoProcesoField;
            }
            set {
                if ((this.TiempoProcesoField.Equals(value) != true)) {
                    this.TiempoProcesoField = value;
                    this.RaisePropertyChanged("TiempoProceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CentroTrabajoOpcionBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class CentroTrabajoOpcionBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.CTrabajoBusiness CentroTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CentroTrabajoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroTrabajoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroTrabajoObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpcionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OpcionLavadoBusiness OpcionLavadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.CTrabajoBusiness CentroTrabajo {
            get {
                return this.CentroTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoField, value) != true)) {
                    this.CentroTrabajoField = value;
                    this.RaisePropertyChanged("CentroTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CentroTrabajoId {
            get {
                return this.CentroTrabajoIdField;
            }
            set {
                if ((this.CentroTrabajoIdField.Equals(value) != true)) {
                    this.CentroTrabajoIdField = value;
                    this.RaisePropertyChanged("CentroTrabajoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroTrabajoNombre {
            get {
                return this.CentroTrabajoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoNombreField, value) != true)) {
                    this.CentroTrabajoNombreField = value;
                    this.RaisePropertyChanged("CentroTrabajoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroTrabajoObservacion {
            get {
                return this.CentroTrabajoObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroTrabajoObservacionField, value) != true)) {
                    this.CentroTrabajoObservacionField = value;
                    this.RaisePropertyChanged("CentroTrabajoObservacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpcionId {
            get {
                return this.OpcionIdField;
            }
            set {
                if ((this.OpcionIdField.Equals(value) != true)) {
                    this.OpcionIdField = value;
                    this.RaisePropertyChanged("OpcionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.OpcionLavadoBusiness OpcionLavado {
            get {
                return this.OpcionLavadoField;
            }
            set {
                if ((object.ReferenceEquals(this.OpcionLavadoField, value) != true)) {
                    this.OpcionLavadoField = value;
                    this.RaisePropertyChanged("OpcionLavado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpcionLavadoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class OpcionLavadoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.LavadoBusiness LavadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LavadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.TelaBusiness TelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.LavadoBusiness Lavado {
            get {
                return this.LavadoField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoField, value) != true)) {
                    this.LavadoField = value;
                    this.RaisePropertyChanged("Lavado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LavadoId {
            get {
                return this.LavadoIdField;
            }
            set {
                if ((this.LavadoIdField.Equals(value) != true)) {
                    this.LavadoIdField = value;
                    this.RaisePropertyChanged("LavadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.TelaBusiness Tela {
            get {
                return this.TelaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaField, value) != true)) {
                    this.TelaField = value;
                    this.RaisePropertyChanged("Tela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaId {
            get {
                return this.TelaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaIdField, value) != true)) {
                    this.TelaIdField = value;
                    this.RaisePropertyChanged("TelaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LavadoBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class LavadoBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ColoresIntermodaBusiness ColorIntermodaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LavadoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LavadoFechaActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LavadoFechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LavadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LavadoNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColorId {
            get {
                return this.ColorIdField;
            }
            set {
                if ((this.ColorIdField.Equals(value) != true)) {
                    this.ColorIdField = value;
                    this.RaisePropertyChanged("ColorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ColoresIntermodaBusiness ColorIntermoda {
            get {
                return this.ColorIntermodaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorIntermodaField, value) != true)) {
                    this.ColorIntermodaField = value;
                    this.RaisePropertyChanged("ColorIntermoda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsActivo {
            get {
                return this.IsActivoField;
            }
            set {
                if ((this.IsActivoField.Equals(value) != true)) {
                    this.IsActivoField = value;
                    this.RaisePropertyChanged("IsActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LavadoDescripcion {
            get {
                return this.LavadoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoDescripcionField, value) != true)) {
                    this.LavadoDescripcionField = value;
                    this.RaisePropertyChanged("LavadoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LavadoFechaActualizacion {
            get {
                return this.LavadoFechaActualizacionField;
            }
            set {
                if ((this.LavadoFechaActualizacionField.Equals(value) != true)) {
                    this.LavadoFechaActualizacionField = value;
                    this.RaisePropertyChanged("LavadoFechaActualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LavadoFechaCreacion {
            get {
                return this.LavadoFechaCreacionField;
            }
            set {
                if ((this.LavadoFechaCreacionField.Equals(value) != true)) {
                    this.LavadoFechaCreacionField = value;
                    this.RaisePropertyChanged("LavadoFechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LavadoId {
            get {
                return this.LavadoIdField;
            }
            set {
                if ((this.LavadoIdField.Equals(value) != true)) {
                    this.LavadoIdField = value;
                    this.RaisePropertyChanged("LavadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LavadoNombre {
            get {
                return this.LavadoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.LavadoNombreField, value) != true)) {
                    this.LavadoNombreField = value;
                    this.RaisePropertyChanged("LavadoNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class TelaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComposicionNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaterialCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelaNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComposicionNombre {
            get {
                return this.ComposicionNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ComposicionNombreField, value) != true)) {
                    this.ComposicionNombreField = value;
                    this.RaisePropertyChanged("ComposicionNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaterialCodigo {
            get {
                return this.MaterialCodigoField;
            }
            set {
                if ((this.MaterialCodigoField.Equals(value) != true)) {
                    this.MaterialCodigoField = value;
                    this.RaisePropertyChanged("MaterialCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaCodigo {
            get {
                return this.TelaCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaCodigoField, value) != true)) {
                    this.TelaCodigoField = value;
                    this.RaisePropertyChanged("TelaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaDescripcion {
            get {
                return this.TelaDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaDescripcionField, value) != true)) {
                    this.TelaDescripcionField = value;
                    this.RaisePropertyChanged("TelaDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelaNombre {
            get {
                return this.TelaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.TelaNombreField, value) != true)) {
                    this.TelaNombreField = value;
                    this.RaisePropertyChanged("TelaNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColoresIntermodaBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class ColoresIntermodaBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObservacionOperacionServiceReference.IObservacionOperacion")]
    public interface IObservacionOperacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/Update", ReplyAction="http://tempuri.org/IObservacionOperacion/UpdateResponse")]
        Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness Update(Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness observacionOperacionBusiness);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/Update", ReplyAction="http://tempuri.org/IObservacionOperacion/UpdateResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness observacionOperacionBusiness);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/Delete", ReplyAction="http://tempuri.org/IObservacionOperacion/DeleteResponse")]
        void Delete(int observacionOperacionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/Delete", ReplyAction="http://tempuri.org/IObservacionOperacion/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int observacionOperacionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/Get", ReplyAction="http://tempuri.org/IObservacionOperacion/GetResponse")]
        Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness Get(int observacionOperacionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/Get", ReplyAction="http://tempuri.org/IObservacionOperacion/GetResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness> GetAsync(int observacionOperacionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/GetAll", ReplyAction="http://tempuri.org/IObservacionOperacion/GetAllResponse")]
        Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/GetAll", ReplyAction="http://tempuri.org/IObservacionOperacion/GetAllResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/GetByOperacionProceso", ReplyAction="http://tempuri.org/IObservacionOperacion/GetByOperacionProcesoResponse")]
        Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness[] GetByOperacionProceso(int operacionProcesoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObservacionOperacion/GetByOperacionProceso", ReplyAction="http://tempuri.org/IObservacionOperacion/GetByOperacionProcesoResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness[]> GetByOperacionProcesoAsync(int operacionProcesoId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObservacionOperacionChannel : Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.IObservacionOperacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObservacionOperacionClient : System.ServiceModel.ClientBase<Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.IObservacionOperacion>, Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.IObservacionOperacion {
        
        public ObservacionOperacionClient() {
        }
        
        public ObservacionOperacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObservacionOperacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObservacionOperacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObservacionOperacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness Update(Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness observacionOperacionBusiness) {
            return base.Channel.Update(observacionOperacionBusiness);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness observacionOperacionBusiness) {
            return base.Channel.UpdateAsync(observacionOperacionBusiness);
        }
        
        public void Delete(int observacionOperacionId) {
            base.Channel.Delete(observacionOperacionId);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int observacionOperacionId) {
            return base.Channel.DeleteAsync(observacionOperacionId);
        }
        
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness Get(int observacionOperacionId) {
            return base.Channel.Get(observacionOperacionId);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness> GetAsync(int observacionOperacionId) {
            return base.Channel.GetAsync(observacionOperacionId);
        }
        
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness[] GetByOperacionProceso(int operacionProcesoId) {
            return base.Channel.GetByOperacionProceso(operacionProcesoId);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.ObservacionOperacionServiceReference.ObservacionOperacionBusiness[]> GetByOperacionProcesoAsync(int operacionProcesoId) {
            return base.Channel.GetByOperacionProcesoAsync(operacionProcesoId);
        }
    }
}
