//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubClaseBusiness", Namespace="http://schemas.datacontract.org/2004/07/Intermoda.Business.Lavanderia")]
    [System.SerializableAttribute()]
    public partial class SubClaseBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CompaniaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CompaniaCodigo {
            get {
                return this.CompaniaCodigoField;
            }
            set {
                if ((this.CompaniaCodigoField.Equals(value) != true)) {
                    this.CompaniaCodigoField = value;
                    this.RaisePropertyChanged("CompaniaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubClaseServiceReference.ISubClase")]
    public interface ISubClase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubClase/Update", ReplyAction="http://tempuri.org/ISubClase/UpdateResponse")]
        Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness Update(Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness subClase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubClase/Update", ReplyAction="http://tempuri.org/ISubClase/UpdateResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness subClase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubClase/Delete", ReplyAction="http://tempuri.org/ISubClase/DeleteResponse")]
        void Delete(string subClaseCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubClase/Delete", ReplyAction="http://tempuri.org/ISubClase/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string subClaseCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubClase/Get", ReplyAction="http://tempuri.org/ISubClase/GetResponse")]
        Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness Get(string subClaseCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubClase/Get", ReplyAction="http://tempuri.org/ISubClase/GetResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness> GetAsync(string subClaseCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubClase/GetAll", ReplyAction="http://tempuri.org/ISubClase/GetAllResponse")]
        Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubClase/GetAll", ReplyAction="http://tempuri.org/ISubClase/GetAllResponse")]
        System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubClaseChannel : Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.ISubClase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubClaseClient : System.ServiceModel.ClientBase<Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.ISubClase>, Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.ISubClase {
        
        public SubClaseClient() {
        }
        
        public SubClaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubClaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubClaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubClaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness Update(Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness subClase) {
            return base.Channel.Update(subClase);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness> UpdateAsync(Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness subClase) {
            return base.Channel.UpdateAsync(subClase);
        }
        
        public void Delete(string subClaseCodigo) {
            base.Channel.Delete(subClaseCodigo);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string subClaseCodigo) {
            return base.Channel.DeleteAsync(subClaseCodigo);
        }
        
        public Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness Get(string subClaseCodigo) {
            return base.Channel.Get(subClaseCodigo);
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness> GetAsync(string subClaseCodigo) {
            return base.Channel.GetAsync(subClaseCodigo);
        }
        
        public Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Intermoda.ClientProxy.Lavanderia.SubClaseServiceReference.SubClaseBusiness[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
