//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CantidadIngredientesInstruccion
    {
        public int CantidadIngredienteInstruccionId { get; set; }
        public int CantidadIngredienteInstruccionCiaCod { get; set; }
        public int CantidadIngredienteInstruccionPlantaCod { get; set; }
        public int CantidadIngredienteInstruccionAnio { get; set; }
        public int CantidadIngredienteInstruccionNumeroOrden { get; set; }
        public short CantidadIngredienteInstruccionCargaLavadoNumero { get; set; }
        public int CantidadIngredienteInstruccionLavadoId { get; set; }
        public int CantidadIngredienteInstruccionOpcionLavadoId { get; set; }
        public int CantidadIngredienteInstruccionOperacionId { get; set; }
        public int CantidadIngredienteInstruccionInstruccionId { get; set; }
        public int CantidadIngredienteInstruccionMaterialId { get; set; }
        public Nullable<decimal> CantidadIngredienteInstruccionValor { get; set; }
    }
}
