//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOG
    {
        public int MapCodMat { get; set; }
        public string CataDesLar { get; set; }
        public string CataDesCor { get; set; }
        public string MedCompra { get; set; }
        public string MedConsum { get; set; }
        public string TipRCod { get; set; }
        public string CataGru { get; set; }
        public string MapCtaCont { get; set; }
        public string MapCtaVF { get; set; }
        public string MapCtaCon2 { get; set; }
        public string MapNum1Rep { get; set; }
        public string PrdCodTel { get; set; }
        public string MatGrpDes { get; set; }
        public Nullable<int> MatGrpCod { get; set; }
    }
}
