//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientesPreDefinidos
    {
        public int IngredientePreDefinidoId { get; set; }
        public int IngredienteId { get; set; }
        public int OperacionId { get; set; }
        public string IngredientePreDefinidoClaseId { get; set; }
        public string IngredientePreDefinidoSubClaseId { get; set; }
        public Nullable<decimal> IngredientePreDefinidoPorcentaje { get; set; }
        public Nullable<int> IngredientePreDefinidoOrden { get; set; }
        public Nullable<int> IngredientePreDefinidoInstruccionesOperacionId { get; set; }
    
        public virtual InstruccionesPreDefinidas InstruccionesPreDefinidas { get; set; }
        public virtual OperacionesPreDefinidas OperacionesPreDefinidas { get; set; }
    }
}
