//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lavadoras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lavadoras()
        {
            this.CargaLavado = new HashSet<CargaLavado>();
        }
    
        public short LavadoraId { get; set; }
        public string LavadoraNombre { get; set; }
        public short LavadorasCapacidadId { get; set; }
        public string LavadoraMarca { get; set; }
        public string LavadoraModelo { get; set; }
        public short LavadoraEstado { get; set; }
        public string LavadoraNumeroSerie { get; set; }
        public string LavadoraIP { get; set; }
        public string LavadoraMAC { get; set; }
    
        public virtual LavadorasCapacidad LavadorasCapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargaLavado> CargaLavado { get; set; }
    }
}
