//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialNoRequisableLavanderia
    {
        public int MaterialNoRequisableLavanderiaId { get; set; }
        public int CodigoMaterial { get; set; }
        public string Descripcion { get; set; }
        public double PorcentajeUtilizacion { get; set; }
    }
}
