//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesosCentroTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcesosCentroTrabajo()
        {
            this.OperacionesProceso = new HashSet<OperacionesProceso>();
        }
    
        public int ProcesoCentroTrabajoId { get; set; }
        public int ProcesoId { get; set; }
        public int CentroTrabajoId { get; set; }
        public int CentroTrabajoOpcionId { get; set; }
        public int ProcesoCentroTrabajoOrden { get; set; }
    
        public virtual CentrosTrabajoOpcion CentrosTrabajoOpcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacionesProceso> OperacionesProceso { get; set; }
    }
}
