//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermoda.Produccion.Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBCLASE
    {
        public short CIACOD { get; set; }
        public string MprCodSCla { get; set; }
        public string MprDesSCla { get; set; }
        public string MprSClaSts { get; set; }
        public string MprSClaAX { get; set; }
    }
}
